### ISSUE TITLE
Error: data out-of-bounds when scraping transaction hash that contains ERC-721 TokenID 

### ISSUE THREAD

**Issue by developer9** [Linch1/Web3TokenCharting#11]
When running price scraper from the start block, the below error occurs.

Looking at the transaction hash, it contains ERC-721 transfer or mint.

`Had error:  0x65269b3f27fd7485049887e0165d1880006cf85ca8706eb03fc011864525c584 Error: data out-of-bounds (length=0, offset=32, code=BUFFER_OVERRUN, version=abi/5.5.0)` 

Thanks

**Comment by Linch1** [comment]
Hello, I'm aware of this, since i was not interested in erc-721 i just inserted a try catch to detect it.

It is causing issues ?

**Comment by developer9** [comment]
> Hello, I'm aware of this, since i was not interested in erc-721 i just inserted a try catch to detect it.
> 
> It is causing issues or was bad to see it 🥲 ?

Ah ok. No issues. Just thought to bring to your attention. All good. Thanks
