### ISSUE TITLE
Help me queue !!

### ISSUE THREAD

**Issue by tanhsnkt1997** [Linch1/Web3TokenCharting#13]
![image](https://user-images.githubusercontent.com/45147625/177282635-c01213e2-7689-4ab7-b0c6-d3d74c01758e.png)

What happens if i change number of queue  from 100 to 1000 or 10 , is it fast ? If i want change speed scrap, What should i do ??

**Comment by Linch1** [comment]
Hello, yeah it should do that ideally, but tbh i'm not sure if it works in reality, you can try that and see how it goes :+1:

**Comment by tanhsnkt1997** [comment]
if i change 100 to 1000 are 1000 processes running concurrently ?

**Comment by tanhsnkt1997** [comment]
I start from special block => scrap very slow, i think queue problem

**Comment by tanhsnkt1997** [comment]
I fixed
