### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by etulikov** [Linch1/Web3TokenCharting#14]
Hello!

Can you help me to understand a couple of things?

1. What mean this? And how you found them?
`let swapSign = "0xd78ad95fa46c994b6551d0da85fc275fe613ce37657fb8d5e3d130840159d822";
let syncSign = "0x1c411e9a96e071241c2f21f7726b17ae89e3cab4c78be50e062b03a9fffbbad1";
let transferSign = "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef";`

2. How to parse more swaps? I want to add Biswap, 1inch and others?

3. And the last one :) How to add more networks to this scraper? 

Thank you very much for your job!

**Comment by Linch1** [comment]
Hello :)

1) Check this video https://www.youtube.com/watch?v=ClOATp_GuM4&ab_channel=Gasvard , the signature is like a fingerprint of the events that you want to listen

2) Theorically the `sync` singature currently used in this project is the one that identifies the sync event used by 95% of the dex on evm networks, if you want to add some custom dex that you see are not currently scraped from the bot i think you will have to dig a bit inside the repo code and understand/customize it. I'm working a new version that will include biswap like dexes but not sure on when it will be online

3) currently there is no easy way to add more networks, working on that also in the new version, at the moment you can only dig into the repo and customize it as you want also for this one
