### ISSUE TITLE
Token Histories collection

### ISSUE THREAD

**Issue by etulikov** [Linch1/Web3TokenCharting#15]
Hello! can you explain why we need **tokenhistories** collection?

**Comment by Linch1** [comment]
Hello, the naming is not the best but basically it holds the information for a token pair, so each record represent a pair with its informations, like, the tokens inside the pair, the pair value in $, the reserves holdings in the pair etc..

It is used for example:

in the scraper to check if a pair is already present in the db https://github.com/Linch1/WeChartWeb3/blob/9234aca9a446fa58d0053f3bc19276e8a964b8ea/workers/updater/lib/Scraper.js#L220

and from the server to get all the pairs of one specific token 
https://github.com/Linch1/WeChartWeb3/blob/9234aca9a446fa58d0053f3bc19276e8a964b8ea/server/routes/tokens/token.js#L60
