### ISSUE TITLE
Error when Running it

### ISSUE THREAD

**Issue by DiMiTriFrog** [Linch1/Web3TokenCharting#17]
After running.
`sudo pm2 startup`
and 
`sudo pm2 start npm --name "charting-bot-restarter" -- run restarter`

I can check there are error with the charting-bog. Here the logs and capture. I dont know how solve it.

```
1|charting-bot  |     at require (internal/modules/cjs/helpers.js:74:18)
1|charting-bot  |     at Object.<anonymous> (/root/WeChartWeb3-master/workers/lib/block.listner.js:1:33)
1|charting-bot  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
1|charting-bot  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
1|charting-bot  |     at Module.load (internal/modules/cjs/loader.js:863:32)
1|charting-bot  |     at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
1|charting-bot  |   code: 'MODULE_NOT_FOUND',
1|charting-bot  |   requireStack: [
1|charting-bot  |     '/root/WeChartWeb3-master/workers/lib/web3.js',
1|charting-bot  |     '/root/WeChartWeb3-master/workers/lib/block.listner.js',
1|charting-bot  |     '/root/WeChartWeb3-master/workers/lib/scrape.block.stream.js',
1|charting-bot  |     '/root/WeChartWeb3-master/workers/updater/master.js'
1|charting-bot  |   ]
1|charting-bot  | }
```
![IMG_0B8E11F819DA-1](https://user-images.githubusercontent.com/38754548/184838377-eb44a5ed-7c0e-488e-be80-3d59e9715c23.jpeg)

Thanks!

**Comment by DiMiTriFrog** [comment]
At this moment seems is solved but when run npm run server i have this loop output:
![IMG_CACA95AA3260-1](https://user-images.githubusercontent.com/38754548/184839668-de81754e-b4c6-4dea-b0d5-2b85ea9e96ab.jpeg)

**Comment by Linch1** [comment]
Ehi :)

Have you created the `.env` file?
it seems that the variable `process.env.FRONTEND_URL` is missing from your `.env` file

**Comment by DiMiTriFrog** [comment]
Hi!  Thanks for response.
The FRONTEND_URL is the url of node?
