### ISSUE TITLE
historytransactions tokenIn&tokenOut recorded same contract address issue

### ISSUE THREAD

**Issue by GuolongCyber** [Linch1/Web3TokenCharting#19]
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/83916371/187082044-5919317c-c954-4299-9be4-b7ae5a4befa3.png">

<img width="902" alt="image" src="https://user-images.githubusercontent.com/83916371/187082069-fbbe3a04-25f6-432a-a0a0-6d27ae2bacf2.png">
It seems that this is the issue:
https://github.com/Linch1/WeChartWeb3/blob/master/workers/updater/lib/Scraper.js#L355

**Comment by Linch1** [comment]
Ehi It should now work correctly, thanks for the report :+1: :smile:
