### ISSUE TITLE
How to Scrape from the first block

### ISSUE THREAD

**Issue by eksion** [Linch1/Web3TokenCharting#4]
Hello, on which part i need to change, if i want to start the scrape from the specific block ?

**Comment by Linch1** [comment]
Hello, I've not tested this snippet of code, but you should replace lines 187-222 inside the file 

https://github.com/Linch1/Web3TokenCharting/blob/f95acadbffadafdfa0c356a7395c9d851f4426e4/workers/scraper-price.js#L187

with this code

```
let queue = new Queue(100, logCallback);
    let filter = [ syncSign ];

    let scrapedTxs = []; 
    async function logCallback(error, hash){
        if( error ) return console.log( error );
        if( scrapedTxs.indexOf(hash) != -1 ) return;
        
        scrapedTxs.push(hash);
        let receipt;
        try {
            receipt = await web3_https.eth.getTransactionReceipt(hash);
        } catch (error) {
            return console.log('[RECEIPT ERR]', error);
        }
        if(!receipt) return;
        
        let relevantEvents = organizeEvents(hash, receipt);
        // printEvents( hash, relevantEvents );

        for( let pair in relevantEvents ) scanTransactionCallback( hash, pair, relevantEvents[pair] );
    }
 
    let startBlock = 0;
    while ( startBlock != await web3_https.eth.getBlockNumber() ){
        let blockInfo = await web3_https.eth.getBlock();
        for( let hash of blockInfo.transactions){
            queue.add(error, hash) 
        }
        await sleep(100);
    }
```

Specifying the `startBlock` variable you will scrape from that block. Be aware that scraping from the intial block will take a considerable amount of time.

Assuming that you are able to get all the information of a block transactions in 0.5seconds, than you would need ~ 100 days to scrape all the existant block
