### ISSUE TITLE
Missing examle .env stated in L19 of readme.md

### ISSUE THREAD

**Issue by ultra-pool** [Linch1/Web3TokenCharting#5]
https://github.com/Linch1/Web3TokenCharting/blob/master/readme.md?plain=1#L19

Missing the example .env file stated in the readme.md can you provide this?

**Comment by Linch1** [comment]
cannot update the repo atm, but here is the sctructure of the `.env`
```
PROVIDER_WSS=<WSS_PROVIDER>
PROVIDER_HTTPS=<HTTPS_PROVIDER>
PORT=5006
WRITE_TO_DB_SECONDS=60
FRONTEND_URL=["http://localhost:5005", "http://localhost:5003"]
```

**Comment by ultra-pool** [comment]
Great thank you

**Comment by karbagasurendran** [comment]
> cannot update the repo atm, but here is the sctructure of the `.env`
> 
> ```
> PROVIDER_WSS=<WSS_PROVIDER>
> PROVIDER_HTTPS=<HTTPS_PROVIDER>
> PORT=5006
> WRITE_TO_DB_SECONDS=60
> FRONTEND_URL=["http://localhost:5005", "http://localhost:5003"]
> ```

What is process.env.SERVER_VOTING url @Linch1 .
please provide url information @Linch1
