### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by ghost** [Linch1/Web3TokenCharting#7]
Hello, can you help with the installation, for a fee. I didn't. jetblackif@gmail.com

**Comment by Linch1** [comment]
Hello, installation is pretty simple

- install mongodb community edition
- install nodejs
- install npm

- create a `.env` file and populate it with the content inside the `.env.example` file
- set the `.env` variables `PROVIDER_WSS` and `PROVIDER_HTTPS` with valid node providers urls

- run `npm i`
- run `npm run scraper` in the background and let it run
