### ISSUE TITLE
Price Scrapper for specific pair

### ISSUE THREAD

**Issue by developer9** [Linch1/Web3TokenCharting#9]
Hi @Linch1 , 

Thanks for the script. 

Just a question, how to run price scrapper for specific token or pair? 

Thanks

**Comment by developer9** [comment]
Actually, some tokens I see only 1 or 2 transactions only. OHLC data is not getting updated. Any help to point me in right direction is appreciated? THanks

**Comment by Linch1** [comment]
Hello, if you want to run the bot just for a specific token you should insert an `if statement` on this line

https://github.com/Linch1/Web3TokenCharting/blob/34a8ee69b148a27833b21e7504dedd624df0d738/workers/scraper-price/Scraper.js#L73

where you check that the pair address that is going to be analized is inside a list of 'whitelisted' pair addresses. 
For example:

```
let whitelistedPairs = [ '0x58f876857a02d6762e0101bb5c46a8c1ed44dc16' ];
if ( !whitelistedPairs.includes (pair) ) return;
``` 

I did not test this but should do the trick

**Comment by Linch1** [comment]
> e tokens I see only 1 or 2 transactions only. OHLC data is

So it detects less transactions than the one that are being made or you are saying something else ?

**Comment by developer9** [comment]
> Hello, if you want to run the bot just for a specific token you should insert an `if statement` on this line
> 
> https://github.com/Linch1/Web3TokenCharting/blob/34a8ee69b148a27833b21e7504dedd624df0d738/workers/scraper-price/Scraper.js#L73
> 
> where you check that the pair address that is going to be analized is inside a list of 'whitelisted' pair addresses. For example:
> 
> ```
> let whitelistedPairs = [ '0x58f876857a02d6762e0101bb5c46a8c1ed44dc16' ];
> if ( !whitelistedPairs.includes (pair) ) return;
> ```
> 
> I did not test this but should do the trick

Thank you. will test it and confirm.

**Comment by developer9** [comment]
> > e tokens I see only 1 or 2 transactions only. OHLC data is
> 
> So it detects less transactions than the one that are being made or you are saying something else ?

historytransactions and historyprices collection is not getting updated for all the pairs. 

For instance, 0xc748673057861a797275CD8A068AbB95A902e8de  this is scraped and can query from tokenbasics, tokenhistories and  pairs collection but historytransactions and historyprices collection won't have the recent OHLC and transactions data.

**Comment by Linch1** [comment]
Ok thanks for the report going to check this days and get back to you :+1:

**Comment by developer9** [comment]
> Ok thanks for the report going to check this days and get back to you 👍

Sorry, the token is not in the "Pairs" collection. Can I manually update it?

**Comment by Linch1** [comment]
> Hello, if you want to run the bot just for a specific token you should insert an `if statement` on this line
> 
> https://github.com/Linch1/Web3TokenCharting/blob/34a8ee69b148a27833b21e7504dedd624df0d738/workers/scraper-price/Scraper.js#L73
> 
> where you check that the pair address that is going to be analized is inside a list of 'whitelisted' pair addresses. For example:
> 
> ```
> let whitelistedPairs = [ '0x58f876857a02d6762e0101bb5c46a8c1ed44dc16' ];
> if ( !whitelistedPairs.includes (pair) ) return;
> ```
> 
> I did not test this but should do the trick

Ehi what is the "Pairs" callection you are referring to ?

if you mean the `whitelistedPairs` i mentioned in this example yeah you can edit this, just find the pair address that you want to whitelist and add it

**Comment by developer9** [comment]
> > Hello, if you want to run the bot just for a specific token you should insert an `if statement` on this line
> > https://github.com/Linch1/Web3TokenCharting/blob/34a8ee69b148a27833b21e7504dedd624df0d738/workers/scraper-price/Scraper.js#L73
> > 
> > where you check that the pair address that is going to be analized is inside a list of 'whitelisted' pair addresses. For example:
> > ```
> > let whitelistedPairs = [ '0x58f876857a02d6762e0101bb5c46a8c1ed44dc16' ];
> > if ( !whitelistedPairs.includes (pair) ) return;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I did not test this but should do the trick
> 
> Ehi what is the "Pairs" callection you are referring to ?
> 
> if you mean the `whitelistedPairs` i mentioned in this example yeah you can edit this, just find the pair address that you want to whitelist and add it

Thanks. Here is the Pair schema file: server/models/pair.js that inserts into "Pairs" MongoDB collection.  Pairs collection is missing the Pair record for the specific tokens that do not have historyprices and historytransactions data. 

Now I am running the "pairs-update" from first pair index to see if it fixes it. I will let you know how it goes. Thanks again for your time.

**Comment by Linch1** [comment]
Ok thanks, 
so just a recap

- token you are facing issue: `0xc748673057861a797275CD8A068AbB95A902e8de`
- Issue: The transaction do not trigget the insert of new records inside the following models
[pair.js](https://github.com/Linch1/Web3TokenCharting/blob/master/server/models/pair.js)
[history_transactions.js](https://github.com/Linch1/Web3TokenCharting/blob/master/server/models/history_transactions.js)
[history_prices.js](https://github.com/Linch1/Web3TokenCharting/blob/master/server/models/history_prices.js)
instead the models tokenbasics, tokenhistories are populated correctly. 

is this correct?

**Comment by developer9** [comment]
> Ok thanks, so just a recap
> 
> * token you are facing issue: `0xc748673057861a797275CD8A068AbB95A902e8de`
> * Issue: The transaction do not trigget the insert of new records inside the following models
>   [pair.js](https://github.com/Linch1/Web3TokenCharting/blob/master/server/models/pair.js)
>   [history_transactions.js](https://github.com/Linch1/Web3TokenCharting/blob/master/server/models/history_transactions.js)
>   [history_prices.js](https://github.com/Linch1/Web3TokenCharting/blob/master/server/models/history_prices.js)
>   instead the models tokenbasics, tokenhistories are populated correctly.
> 
> is this correct?

Yes, that's correct. 

Also, could you please confirm the sequence of the scraper?  

My understanding is the below: 

-  Scan for pairs
-  Insert pairs
-  scan for transactions related to the saved pairs
-  for each transaction detect swap, update the historyprices and update historytransactions


>

**Comment by Linch1** [comment]
Ok thanks.

Nope it's it does the following:
Knowing that the `Sync` event is emitted every time that a  pair changes it's reserves ( mostly for new swaps inside that pair )

- listen for all the `Sync` events on the chain
- when a transaction with inside a `Sync` is detected, it gets the tx `receipt` with the relative logs
- analize and organize the receipt logs
- for each synced pair in that transaction
- if the pair is not known, save it
- if the tokens inside the pair are not known, save them
- update the pair reserves,  historyprices and historytransactions

**Comment by Linch1** [comment]
So i've tested this, and actually on my end it is populating the transactions and prices for the token `0xc748673057861a797275CD8A068AbB95A902e8de`

I've added a new file `config.js` with a whitelist option as you asked for :)
just enable it and insert the token you want to have in the whitelist

If you can do this to check if it is correctly working would be great: 
- clear the db or use a new one, (server/config/db.js)
- enable the whitelist and insert only the token `0xc748673057861a797275CD8A068AbB95A902e8de`
- wait few minutes and check if something is populated in the db

**Comment by developer9** [comment]
> So i've tested this, and actually on my end it is populating the transactions and prices for the token `0xc748673057861a797275CD8A068AbB95A902e8de`
> 
> I've added a new file `config.js` with a whitelist option as you asked for :) just enable it and insert the token you want to have in the whitelist
> 
> If you can do this to check if it is correctly working would be great:
> 
> * clear the db or use a new one, (server/config/db.js)
> * enable the whitelist and insert only the token `0xc748673057861a797275CD8A068AbB95A902e8de`
> * wait few minutes and check if something is populated in the db

Thank you so much. Will check it out and confirm.

**Comment by tanhsnkt1997** [comment]
@Linch1  Can you help me, I want scrap with specific  block

**Comment by developer9** [comment]
> @Linch1 Can you help me, I want scrap with specific block

Please check this comment https://github.com/Linch1/Web3TokenCharting/issues/4#issuecomment-1094228584

**Comment by Linch1** [comment]
@tanhsnkt1997 yes as @developer9 mentioned you can use that trick :)

Otherwise you can wait some days ( up to 1-2 week maybe, not sure abou when it will be completed ) and i'll publish an emproved version of the scraper with also this feature

**Comment by developer9** [comment]
> So i've tested this, and actually on my end it is populating the transactions and prices for the token `0xc748673057861a797275CD8A068AbB95A902e8de`
> 
> I've added a new file `config.js` with a whitelist option as you asked for :) just enable it and insert the token you want to have in the whitelist
> 
> If you can do this to check if it is correctly working would be great:
> 
> * clear the db or use a new one, (server/config/db.js)
> * enable the whitelist and insert only the token `0xc748673057861a797275CD8A068AbB95A902e8de`
> * wait few minutes and check if something is populated in the db

Hey @Linch1 It is working for this token. Please feel free to close this issue.  If you don't mind answering the below otherwise I can raise another issue.

But I see this in the console log " [PAIR] Not cached " for random tokens.  Any idea? Thanks

**Comment by Linch1** [comment]
Ok great thanks.
That's a normal log :+1: , it means that the scraped pair is not yet in the scraper cache, but will be added right after that log to avoid querying it from the database every time.
